CREATE TABLE USR (
ID VARCHAR(32) UNIQUE,
EMAIL VARCHAR(255) UNIQUE,
logtime VARCHAR(32),
primary key (ID)
);

CREATE TABLE SOUNDS (
USR_ID VARCHAR(32),
SND_ID INTEGER,
INSTRUMENT VARCHAR(32),
FILE VARCHAR(255),
ANSWER VARCHAR(10),
logtime VARCHAR(32),
primary key (USR_ID, SND_ID)
);

CREATE TABLE META (
ID INT NOT NULL AUTO_INCREMENT,
USR_ID VARCHAR(32),
META_ID VARCHAR(32),
ANSWER TEXT,
logtime VARCHAR(32),
primary key (ID)
);

